### ISSUE TITLE
parse error on type applications

### ISSUE THREAD

**Issue by ghorn** [guibou/PyF#19]
Not understanding the internals of `PyF`, I have no idea what is involved with supporting type applications. But here is a minimal example:

```haskell
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TypeApplications #-}

module Foo where

import Data.Proxy ( Proxy(..) )
import PyF ( f )

foo :: Proxy a -> String
foo _ = "foo"

-- desired behavior
wow1 :: String
wow1 = foo (Proxy @Int)

-- parse error on @
wow2 :: String
wow2 = [f|{foo (Proxy @Int)}|]  
```
I expect `wow1` and `wow2` to behave the same, but there is a parse error on `wow2`:
```
   |
18 | wow2 = [f|{foo (Proxy @Int)}|]  
   |                       ^
Parse error: @

    • In the quasi-quotation: [f|{foo (Proxy @Int)}|]
   |
18 | wow2 = [f|{foo (Proxy @Int)}|]  
   |           ^^^^^^^^^^^^^^^^^^^^
```

**Comment by guibou** [comment]
Good finding. I just need to configure the expression parsing with the same set of expression than the one available in the current splice.

**Comment by guibou** [comment]
Apparently `haskell-src-meta` used to transform the parsed haskell (using `haskell-src-exts`) to template haskell, does not correctly support `TypeApplications`, see https://github.com/DanBurton/haskell-src-meta/issues/4

in #9 I propose to remove `haskell-src-exts` and `haskell-src-meta` in favor of plain `ghc` API, but I still don't know if it is possible to convert an `HsExpr` (the result of the parsing in the `ghc` library) to `Exp` (the template haskell type).

**Comment by DanBurton** [comment]
I've uploaded a fix in `haskell-src-meta-0.8.2`. The following modification to `PythonSyntax.hs` makes this example work, though I'm not sure if you want to somehow more intelligently discover which extensions to use.

```
import qualified Language.Haskell.Exts.Extension as Extension
...
  let mode = ParseExp.defaultParseMode { ParseExp.extensions = [ Extension.EnableExtension Extension.TypeApplications] }
  case SyntaxTranslate.toExp <$> ParseExp.parseExpWithMode mode s of

**Comment by guibou** [comment]
@DanBurton Hey, thank you! I'll use template haskell to discover the extensions enable at splice site, but else it look perfect. Thank you!

**Comment by guibou** [comment]
Hackage update: https://hackage.haskell.org/package/PyF-0.7.2.0
