### ISSUE TITLE
bad interaction of hlint, -XOverloadedStrings, and PyF

### ISSUE THREAD

**Issue by ghorn** [guibou/PyF#22]
A minimal example to reproduce the issue:
 ```haskell
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE OverloadedStrings #-}

module Foo ( go ) where

import qualified Data.Text as T
import PyF ( f )

go :: T.Text
go = [f|{T.intercalate "blah" listOfText}|]
  where
    listOfText :: [T.Text]
    listOfText = []
```
This causes hlint to say
```
Warning: Unused LANGUAGE pragma
Found:
  {-# LANGUAGE OverloadedStrings #-}
Perhaps you should remove it.

1 hint
```
I suspect this is more of an issue with hlint interacting with quasiquoters than a PyF issue, but I don't understand how either work under the hood.

**Comment by guibou** [comment]
Good point.

I'm not sure this can be fixed. I think that `hlint` does not execute the template haskell so it cannot know that the extension is used. I just opened a hlint issue to discuss that, but I'm not sure a robust solution is possible.

Possible (stupid and not satisfying) workarounds:

- don't use `OverloadedString` inside your PyF expressions. Recall that you can use `let` / `where` expression with PyF. `go` can be written as:

```
go :: T.Text
go = [f|{foo}|]
 where
   listOfText :: [T.Text]
   listOfText = []
   
   foo = T.intercalate "blah" listOfText
```

- set `OverloadedString` from outside (using cabal / stack / bazel / ... compilation flags). This way `hlint` won't do the suggestion.

**Comment by guibou** [comment]
I'm closing, upstream `hlint` was updated to disable theses warnings if the source file uses the `QuasiQuotes` extension.

Note that it was always the case for file using the `TemplateHaskell` extension.
