### ISSUE TITLE
Ignoring line breaks causes text to get discarded in many cases

### ISSUE THREAD

**Issue by benzrf** [guibou/PyF#23]
In the parser, the alternative that catches backslashes which are intended to ignore a subsequent newline can only be selected at the beginning of an item: https://github.com/guibou/PyF/blob/1727e26415dbd3d3ce7c2d8c7d510a89352af635/src/PyF/Internal/PythonSyntax.hs#L88
This doesn't catch cases where a backslash occurs in the middle of raw text rather than immediately after an interpolation or doubled brace, such as this one:
```
[f|Example goes\
here!|]
```
These cases get handled entirely by `rawString`, so they get processed by `escapeChars`, which chokes on the `"\\\n"` and discards the rest of the item (actually, this behavior seems to occur for certain other cases as well where an error message might be more appropriate, like if there's a `"\\ "`).

**Comment by guibou** [comment]
Thank you very much for this report!

This is fixed in #24.
