### ISSUE TITLE
Stackage?

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [guibou/PyF#38]

**Comment by guibou** [comment]
You know what. I was totally ignorant of the stackage ecosystem and thought it was working without any manual work because it was pulling stuffs from hackage.

I'll try to understand how to publish PyF in stackage asap. Thank you for the notification.

**Comment by guibou** [comment]
I always used cabal+nix on all my personal projects and I'm using bazel at work. `PyF` was used to have a `.stack` file, but I removed it because I was not using it.

I'll fix that.

TODO:

- [ ] add back a `.stack` with the latest LTS in CI
- [ ] register `PyF` on stackage.

**Comment by guibou** [comment]
I opened a PR for stackag inclusion, but for now it fails with some boundaries issues. I'll investigate that tomorrow.

**Comment by guibou** [comment]
Apparently `PyF` will be in future stackage nightly. I still need to understand how to get it in a LTS.

**Comment by guibou** [comment]
It was removed from nighly because of the testsuite (I was calling `python` for `python3`, it was not an issue in the nix context, but it is in the debian context of the stackage build).

Good news is that it will be included to lts-14.X as soon as it is included in nighly (and a new lts 14-Y is released).

**Comment by guibou** [comment]
Nightly inclusion is good. Next is LTS inclusion ;)

Most of the issues comes from my really weird test system (which compiles Haskell program and run python ones) ;)

**Comment by BebeSparkelSparkel** [comment]
Great! Thanks for adding this
