### ISSUE TITLE
Is translateTHtoGHCExt just id now?

### ISSUE THREAD

**Issue by luke-clifton** [guibou/PyF#89]
Since `GhcTH` and `TH` are the same, is `translateTHtoGHCExt` now just `id` or am I missing something?

https://github.com/guibou/PyF/blob/1e84ce8893c235ebb2a3022d7eda3e45e7b9f0c5/src/PyF/Internal/Meta.hs#L32-L33

https://github.com/guibou/PyF/blob/1e84ce8893c235ebb2a3022d7eda3e45e7b9f0c5/src/PyF/Internal/Meta.hs#L211

**Comment by guibou** [comment]
OMG.... Well. What...

Looks like you are perfectly right!

I totally missed that during the refactor ;)

**Comment by guibou** [comment]
Thank a lot ;) I like this kind of code change.
