### ISSUE TITLE
Incorrect version bounds

### ISSUE THREAD

**Issue by sellout** [guibou/PyF#94]
PyF 0.8.1.0 is the last version to work with base <4.11 (GHC <8.4), but the cabal bounds haven't been updated.

This problem also affects revisions 0.8.1.1 and 0.8.1.2, I just point it out because they're not major version bumps from the last one that worked.

Pinning a dependency to `==0.8.1.0` won't work on GHC 8.8+, since it requires `template-haskell <2.15`.

**Comment by sellout** [comment]
Similiarly, PyF 0.8.1.0 requires at least template-haskell 2.13 (maybe even newer?), but the constraint is only `>=2.11`.

**Comment by guibou** [comment]
Hi @sellout, thank you for the report.

Could you open an MR to fix the bounds? I'll approve it super quickly.

If you cannot, I'll do that in the future (but I don't know when ;)

**Comment by sellout** [comment]
That PR just adds bounds to the latest version (and makes some small changes to support GHC 8.6 through 9.2), rather than backporting the bounds or whatever. But I have another change coming that restores support for GHC 8.4 (and hopefully even older versions).
